name: SubPathProject
description: ''
version: '1.231'
author: sony@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: subpathproject
  parentArtefactID: sony@prophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2023-09-26 16:10:18'
pipelines:
  pipelines/NEwPipeline01:
    name: NEwPipeline01
    description: ''
    author: sony@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-09-26 16:10:18'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/Omega:
    name: Omega
    description: ''
    author: pankaj@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-11 11:58:58'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs:
  jobs/newJob001:
    name: newJob001
    description: ''
    fabricUID: 7
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0/1 * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: false
    createdAt: '2024-03-26 10:54:26'
    author: pankaj@prophecy.io
  jobs/newDBJob01:
    name: newDBJob01
    description: ''
    fabricUID: 29
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/NEwPipeline01
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-03-26 10:55:39'
    author: pankaj@prophecy.io
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2023-09-26 16:10:18'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '33':
    projectUID: 33
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DTAcEZUO_team_5/iaRHA2Zs_project_33.git&subPath=
    version: 0.2.4
    isDefault: true
    author: null
    createdAt: '2024-03-11 11:58:33'
  '34':
    projectUID: 34
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DTAcEZUO_team_5/iaRHA2Zs_project_34.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2024-03-11 11:58:33'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
