name: SubPathProject
description: ''
version: '1.10'
author: sony@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: subpathproject
  parentArtefactID: sony@prophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2023-09-26 16:10:18'
pipelines:
  pipelines/NEwPipeline01:
    name: NEwPipeline01
    description: ''
    author: sony@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-09-26 16:10:18'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.2.0
  gems: {}
functions:
  author: null
  createdAt: '2023-09-26 16:10:18'
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
